
<?php 
require('class-voiture.php');
$form = new Form();
echo $form->Header();
echo $form->openForm('Enlevement.php');
echo $form->Title();
$musta = new Form();
echo $musta->img;
echo $musta->nom;
echo $musta->name;
echo $musta->mod;
echo $musta->model;
echo $musta->imat;
echo $musta->ima;
echo $musta->Plaque();
echo $musta->kilo;
echo $musta->Drive();
echo $musta->kma;
echo $musta->km;
echo $musta->usage;
echo $musta->kilo();
echo $musta->mise;
echo $musta->mec;
echo $musta->ag;
echo $musta->Age();
echo $musta->age;
echo $musta->po;
echo $musta->poids;
echo $musta->poi;
echo $musta->Poids();
echo $musta->et;
echo $musta->etat;
$Peug = new Form();
echo $Peug->img='<img src="assets/peugeot-308.jpg" alt="peugeot-308"></p>';
echo $Peug->nom;
echo $Peug->name='Peugeot</p>';
echo $Peug->mod;
echo $Peug->model='peugot-308</p>';
echo $Peug->imat;
echo $Peug->ima="FR00";
echo $Peug->Plaque();
echo $Peug->kilo;
echo $Peug->kma=195000;
echo $Peug->km;
echo $Peug->usage;
echo $Peug->kilo();
echo $Peug->mise;
echo $Peug->mec=2017;
echo $Peug->ag;
echo $Peug->Age();
echo $Peug->age;
echo $Peug->po;
echo $Peug->poids=4000;
echo $Peug->poi;
echo $Peug->Poids();
echo $Peug->et;
echo $Peug->etat="Free</p>";
$Toyo = new Form();
echo $Toyo->img='<img src="assets/toyota-isis.png" alt="toyota"></p>';
echo $Toyo->nom;
echo $Toyo->name='Toyota</p>';
echo $Toyo->mod;
echo $Toyo->model='Toyota isis';
echo $Toyo->imat;
echo $Toyo->ima="DE11";
echo $Toyo->Plaque();
echo $Toyo->kilo;
echo $Toyo->kma=296000;
echo $Toyo->km;
echo $Toyo->usage;
echo $Toyo->kilo();
echo $Toyo->mise;
echo $Toyo->mec=2015;
echo $Toyo->ag;
echo $Toyo->Age();
echo $Toyo->age;
echo $Toyo->po;
echo $Toyo->poids=1654;
echo $Toyo->poi;
echo $Toyo->Poids();
echo $Toyo->et;
echo $Toyo->etat="Free</p>";
$End = new Form();
echo $form->closeForm();
?>